In [1]:
# conda list --export > requirements_conda.txt

In [1]:
from tools.dset_getters import dummy_dset, cvsi_dset

dset = dummy_dset()
dset.__getitem__(0)

(tensor([6, 9, 1, 4, 8, 7, 4, 7, 6, 6, 6, 0, 6, 4, 9, 6, 3, 7, 3, 2, 3, 4, 4, 1,
         9, 1, 2, 4, 3, 4, 3, 1, 5, 8, 1, 1, 7, 9, 1, 3, 8, 3, 4, 5, 8, 0, 9, 2,
         6, 5, 6, 5, 3, 7, 5, 9, 7, 9, 7, 7, 6, 0, 2, 9, 8, 0, 7, 2, 6, 1, 7, 9,
         5, 1, 2, 1, 6, 9, 1, 8, 6, 1, 2, 3, 1, 0, 5, 9, 9, 0, 7, 8, 8, 5, 7, 2,
         3, 5, 0, 2], device='cuda:0'),
 tensor(0., device='cuda:0', dtype=torch.float64))

In [1]:
from tools.dset_getters import dummy_dset, cvsi_dset

dset = cvsi_dset(None)
dset.__getitem__(0)


(tensor([3, 3, 1, 0, 0, 2, 0, 3, 3, 3, 2, 2, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 2, 1,
         2, 2, 0, 0, 1, 0, 1, 3, 0, 1, 1, 3, 1, 2, 1, 1, 3, 2, 3, 2, 1, 2, 2, 3,
         3, 0, 0, 0, 3, 3, 1, 1, 2, 0, 3, 1, 3, 1, 0, 2, 1, 2, 1, 2, 3, 0, 1, 0,
         3, 1, 0, 2, 1, 0, 0, 3, 3, 0, 0, 1, 2, 2, 2, 0, 3, 2, 0, 3, 1, 2, 1, 1,
         1, 0, 2, 0], device='cuda:0'),
 tensor(0, device='cuda:0'))

In [1]:
from torchtext.datasets import AG_NEWS, AmazonReviewFull, SogouNews
from torchtext.data.functional import to_map_style_dataset
from tools.dset_getters import cvsi_dset

#TODO uninstall torchtext after check

# train_iter = AG_NEWS(split='test')
# train_iter = AmazonReviewFull(split='test')
train_iter = SogouNews(split='test')

dset = to_map_style_dataset(train_iter)


print(dset)
print(type(dset))

print(dset.__getitem__(0))

dset = cvsi_dset('train')


print(dset)
print(type(dset))

print(dset.__getitem__(0))


<torchtext.data.functional.to_map_style_dataset.<locals>._MapStyleDataset object at 0x7f83002a3ac0>
<class 'torchtext.data.functional.to_map_style_dataset.<locals>._MapStyleDataset'>
(1, ' ti3 ca1o shi4 jie4 be1i : che2ng fe1i na2 pi2ng he2ng mu4 zi4 yo2u ca1o ji1n pa2i  su4 du4 : ( shuo1 mi2ng : dia3n ji1 zi4 do4ng bo1 fa4ng )\\n  shuo1 mi2ng : dia3n ji1 ga1i a4n niu3 , xua3n ze2 yi1 lu4n ta2n ji2 ke3 ')
<class 'tools.dset_getters.cvsi_dset'>
('TTCCCCAAGGGAATTACCCCAGGTTGTGTGTTGACCTACGGGGAGACGTAGTGAGTCACGTGAGTCAGTGATGACCAATACTGGACCACCCGCAAGGACCGAGGTGAGACACTCAGTTTCTCGAAACCACATACAAGGATACGACCCATTTTATAGAGTGCGACTTGTATGATAGCTTTGCCAACTTAGGTTTTGGTCAA', 0)


In [3]:
from tools.basic_model import NeuralNetwork
from tools.dset_getters import dummy_dset, cvsi_dset
from torch.utils.data import DataLoader
import torch 
import numpy as np

dset = cvsi_dset('train')
# dset = cvsi_dset('test')



dummy = NeuralNetwork(4).cuda()

def coll(batch):
    mapper = {
        'A':0,
        'C':1,
        'T':2,
        'G':3,
    }
    xs, ys = [],[]
    for text,label in batch:
        ys.append(torch.tensor(label, dtype=torch.int64))
        # xs.append(torch.tensor([mapper[ch] for ch in text]).to('cuda'))
        xs.append(torch.tensor([mapper[ch] for ch in text], dtype=torch.float32)) #TODO int doesnt work, why?
        

    xs = torch.stack(xs)
    ys = torch.stack(ys)
    return xs.to('cuda'),ys.to('cuda')
    

loader = DataLoader(dset, batch_size=4, shuffle=False, collate_fn=coll)

for el in loader:
    # print('loader element')
    # print(el)
    x,y = el
    # print(x.shape)
    print(dummy(x))
    break

NN INPUT
torch.float32
tensor([[0.1827, 0.2663, 0.2253, 0.2787],
        [0.2090, 0.2481, 0.2422, 0.2517],
        [0.3230, 0.2289, 0.2608, 0.2566],
        [0.2853, 0.2567, 0.2716, 0.2130]], device='cuda:0',
       grad_fn=<SoftmaxBackward>)
