In [1]:
# conda list --export > requirements_conda.txt

In [1]:
from tools.dset_getters import dummy_dset, cvsi_dset

dset = dummy_dset()
dset.__getitem__(0)

(tensor([6, 9, 1, 4, 8, 7, 4, 7, 6, 6, 6, 0, 6, 4, 9, 6, 3, 7, 3, 2, 3, 4, 4, 1,
         9, 1, 2, 4, 3, 4, 3, 1, 5, 8, 1, 1, 7, 9, 1, 3, 8, 3, 4, 5, 8, 0, 9, 2,
         6, 5, 6, 5, 3, 7, 5, 9, 7, 9, 7, 7, 6, 0, 2, 9, 8, 0, 7, 2, 6, 1, 7, 9,
         5, 1, 2, 1, 6, 9, 1, 8, 6, 1, 2, 3, 1, 0, 5, 9, 9, 0, 7, 8, 8, 5, 7, 2,
         3, 5, 0, 2], device='cuda:0'),
 tensor(0., device='cuda:0', dtype=torch.float64))

In [1]:
from tools.dset_getters import dummy_dset, cvsi_dset

dset = cvsi_dset(None)
dset.__getitem__(0)


(tensor([3, 3, 1, 0, 0, 2, 0, 3, 3, 3, 2, 2, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 2, 1,
         2, 2, 0, 0, 1, 0, 1, 3, 0, 1, 1, 3, 1, 2, 1, 1, 3, 2, 3, 2, 1, 2, 2, 3,
         3, 0, 0, 0, 3, 3, 1, 1, 2, 0, 3, 1, 3, 1, 0, 2, 1, 2, 1, 2, 3, 0, 1, 0,
         3, 1, 0, 2, 1, 0, 0, 3, 3, 0, 0, 1, 2, 2, 2, 0, 3, 2, 0, 3, 1, 2, 1, 1,
         1, 0, 2, 0], device='cuda:0'),
 tensor(0, device='cuda:0'))

In [6]:
from torchtext.datasets import IMDB
#TODO uninstall torchtext after check

train_iter = IMDB(split='train')

In [1]:
from tools.basic_model import NeuralNetwork
from tools.dset_getters import dummy_dset, cvsi_dset
from torch.utils.data import DataLoader

dset = cvsi_dset('train')
# dset = cvsi_dset('test')



dummy = NeuralNetwork(4).cuda()

loader = DataLoader(dset, batch_size=8, shuffle=False)

for el in loader:
    x,y = el
    print(x.shape)
    print(dummy(x))
    break

L: 200
L: 200
L: 200
L: 200
L: 200
L: 200
L: 200
L: 200
torch.Size([8, 200])
tensor([[0.1757, 0.1274, 0.1818, 0.1252],
        [0.0960, 0.1211, 0.1599, 0.1128],
        [0.1013, 0.0942, 0.1096, 0.0993],
        [0.1078, 0.1300, 0.1123, 0.1613],
        [0.1155, 0.1292, 0.1186, 0.1265],
        [0.1763, 0.1298, 0.1166, 0.1035],
        [0.1581, 0.1225, 0.1099, 0.1668],
        [0.0694, 0.1458, 0.0914, 0.1047]], device='cuda:0',
       grad_fn=<SoftmaxBackward>)
