In [1]:
# conda list --export > requirements_conda.txt

In [13]:
import os
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader
from tools.dset_getters import cvsi_dset, me_dset
from tools.utils import simple_coll, padding_coll_factory
# from tools.basic_model import NeuralNetwork

In [47]:
# a dummy model with an adjustable number of classes
class NeuralNetwork(nn.Module):
        
    def __init__(self, number_of_classes, vocab_size, embedding_dim, context_size):
        super(NeuralNetwork, self).__init__()
        self.embeddings = nn.Embedding(vocab_size, embedding_dim)
        self.conv1 = nn.Conv1d(in_channels=embedding_dim, out_channels=16, kernel_size=8, bias=True)
        self.norm1 = nn.BatchNorm1d(16)
        self.relu = nn.ReLU()
        self.pool1 = nn.MaxPool1d(2)
        
        self.conv2 = nn.Conv1d(in_channels=16, out_channels=8, kernel_size=8, bias=True)
        self.norm2 = nn.BatchNorm1d(8)
        self.pool2 = nn.MaxPool1d(2)

        self.conv3 = nn.Conv1d(in_channels=8, out_channels=4, kernel_size=8, bias=True)
        self.norm3 = nn.BatchNorm1d(4)
        self.pool3 = nn.MaxPool1d(2)

        self.conv4 = nn.Conv1d(in_channels=4, out_channels=3, kernel_size=8, bias=True)
        self.norm4 = nn.BatchNorm1d(3)
        self.pool4 = nn.MaxPool1d(2)
        
        self.flatten = nn.Flatten()
        self.lin1 = nn.Linear(861, 512)
        self.lin2 = nn.Linear(512, number_of_classes)
        self.sigmoid = nn.Sigmoid()
        self.loss = torch.nn.functional.binary_cross_entropy_with_logits

        
    def forward(self, x):
        x = self.embeddings(x)
        x = x.transpose(1, 2)
        x = self.conv1(x)
        x = self.norm1(x)
        x = self.relu(x)
        x = self.pool1(x)
        
        x = self.conv2(x)
        x = self.norm2(x)
        x = self.relu(x)
        x = self.pool2(x)
        
        x = self.conv3(x)
        x = self.norm3(x)
        x = self.relu(x)
        x = self.pool3(x)
        
        x = self.conv4(x)
        x = self.norm4(x) 
        x = self.relu(x)
        x = self.pool4(x)
        
        x = self.flatten(x)
        x = self.lin1(x) 
        x = self.lin2(x) 
        x = self.sigmoid(x)
        return x

        
    def train_loop(self, dataloader, optimizer):
        for x, y in dataloader:
            optimizer.zero_grad()
            pred = self(x)
#             print('pred: ', pred)
#             print('y: ', y)
            loss = self.loss(pred, y)
#             print(loss)
            loss.backward()
            optimizer.step()
        
#       train acc
# todo: optimize counting of acc
        size = dataloader.dataset.__len__()
        num_batches = len(dataloader)
        train_loss, correct = 0, 0

        with torch.no_grad():
            for X, y in dataloader:
                pred = self(X)
                train_loss += self.loss(pred, y).item()
                correct += (torch.round(pred) == y).sum().item()

#         print('train_loss ', train_loss)
#         print('num_batches', num_batches)
#         print('correct', correct)
#         print('size', size)

        train_loss /= num_batches
        correct /= size
        print(f"Train metrics: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {train_loss:>8f} \n")
            
            
    def train(self, dataloader, epochs):
#         learning_rate = 1e-3
#         TODO use adam
        optimizer = torch.optim.Adam(self.parameters())
        for t in range(epochs):
            print(f"Epoch {t}")
            self.train_loop(dataloader, optimizer)

    def test(self, dataloader):
        size = dataloader.dataset.__len__()
        num_batches = len(dataloader)
        test_loss, correct = 0, 0

        with torch.no_grad():
            for X, y in dataloader:
                pred = self(X)
                test_loss += self.loss(pred, y).item()
                correct += (torch.round(pred) == y).sum().item()

        print('test_loss ', test_loss)
        print('num_batches', num_batches)
        print('correct', correct)
        print('size', size)

        test_loss /= num_batches
        correct /= size
        print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")


In [15]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

get_dataset_fn = me_dset
train_dset = get_dataset_fn('train', force_download=False)


Using cuda device
Reference fasta_cache/Mus_musculus.GRCm38.dna_rm.toplevel.fa.gz already exists. Skipping.


  0%|          | 0/21 [00:00<?, ?it/s]

## Tokenizer and vocab

In [27]:
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import vocab, build_vocab_from_iterator
from collections import Counter 

class LetterTokenizer():
    def __init__(self, **kwargs):
        pass
    def __call__(self, items):
        if isinstance(items, str):
            return self.__tokenize_str(items)
        else:
            return (self.__tokenize_str(t) for t in items)
    def __tokenize_str(self, t):
        tokenized = list(t.replace("\n",""))
        tokenized.append('<eos>')
        tokenized.insert(0,'<bos>')
        return tokenized

tokenizer = get_tokenizer(LetterTokenizer())
# (xx, yy) = zip(*train_dset)

def build_vocab(dataset, tokenizer):
    counter = Counter()
    for i in range(len(dataset)):
        counter.update(tokenizer(dataset[i][0]))
    print(counter.most_common())
    builded_voc = vocab(counter)
    builded_voc.append_token('<pad>')
    return builded_voc

# todo: why build fn does not work as expected (iterator argument)
#     return build_vocab_from_iterator(
#         iterator = counter, 
#         specials = ['<unk>', '<pad>', '<bos>', '<eos>'],
#         special_first = True)

vocabulary = build_vocab(train_dset, tokenizer)
print("vocab len:" ,vocabulary.__len__())
print(vocabulary.get_stoi())

[('N', 694058), ('T', 429929), ('A', 429509), ('C', 356462), ('G', 352072), ('<bos>', 968), ('<eos>', 968)]
vocab len: 8
{'N': 5, '<pad>': 7, 'T': 3, 'C': 4, 'A': 2, '<eos>': 6, 'G': 1, '<bos>': 0}


In [28]:
# tokenizer(train_dset[0][0])
# train_dset[0][0]

In [29]:
# create padding collate 
input_len = max([len(train_dset[i][0]) for i in range(len(train_dset))])
print(input_len)
# padding_coll_factory(longest_length, vocab, tokenizer):
collate = padding_coll_factory(input_len, vocabulary, tokenizer)

train_loader = DataLoader(train_dset, batch_size=32, shuffle=True, collate_fn=collate)


4707


In [30]:
print(next(iter(train_loader))[0][0])
print(next(iter(train_loader))[1][0])
print(next(iter(train_loader))[0][1])
print(next(iter(train_loader))[1][1])

tensor([0, 3, 3,  ..., 7, 7, 7], device='cuda:0')
tensor([0.], device='cuda:0')
tensor([0, 4, 3,  ..., 7, 7, 7], device='cuda:0')
tensor([0.], device='cuda:0')


In [48]:
# __init__(self, number_of_classes, vocab_size, embedding_dim, context_size):
model = NeuralNetwork(
    number_of_classes=1, 
    vocab_size=vocabulary.__len__(),
    embedding_dim=100,
    context_size=input_len
).cuda()
model.train(train_loader, epochs=5)

Epoch 0


/home/jupyter/genomic_benchmarks/tools/utils.py:51: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(tmp, dtype=torch.long)


Train Error: 
 Accuracy: 54.2%, Avg loss: 0.678493 

Epoch 1
Train Error: 
 Accuracy: 59.5%, Avg loss: 0.658285 

Epoch 2
Train Error: 
 Accuracy: 67.9%, Avg loss: 0.636422 

Epoch 3
Train Error: 
 Accuracy: 75.9%, Avg loss: 0.596692 

Epoch 4
Train Error: 
 Accuracy: 78.9%, Avg loss: 0.586691 



In [43]:
test_dset = get_dataset_fn('test', force_download=False)
test_loader = DataLoader(test_dset, batch_size=32, shuffle=True, collate_fn=collate)
model.test(test_loader)

Reference fasta_cache/Mus_musculus.GRCm38.dna_rm.toplevel.fa.gz already exists. Skipping.


  0%|          | 0/21 [00:00<?, ?it/s]

test_loss  4.908510088920593
num_batches 8
correct 185
size 242
Test Error: 
 Accuracy: 76.4%, Avg loss: 0.613564 



In [12]:
for name, param in model.named_parameters():
    print(name, param.requires_grad)

embeddings.weight True
conv1.weight True
norm1.weight True
norm1.bias True
conv2.weight True
norm2.weight True
norm2.bias True
conv3.weight True
norm3.weight True
norm3.bias True
conv4.weight True
norm4.weight True
norm4.bias True
lin1.weight True
lin1.bias True
lin2.weight True
lin2.bias True
